version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: myapp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper-container
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka-container
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  app:
    build:
      context: .
      dockerfile: go.dockerfile
    container_name: logic-standart-app
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - mysql
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - MYSQL_DSN=root:password@tcp(mysql:3306)/myapp
    restart: always

volumes:
  mysql-data:
