// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "golang/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserUC is an autogenerated mock type for the UserUC type
type UserUC struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *UserUC) CreateUser(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserUC creates a new instance of UserUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUC {
	mock := &UserUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
