name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: gohcmus/logic-app
      IMAGE_TAG: v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: gohcmus
          password: +dcvHUqf_==89S!

      - name: Build Docker image
        run: docker build -f go.dockerfile -t gohcm/logic-app:v2

      - name: Push Docker image to Docker Hub
        run: docker push gohcmus/logic-app:v2
