name: Docker Image CI/CD (no security)

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: self-hosted # Hoặc ubuntu-latest nếu không deploy vào Minikube

    env:
      IMAGE_NAME: gohcmus/logic-app
      IMAGE_TAG: v2

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u gohcmus -p +dcvHUqf_==89S!

      - name: Build Docker image
        run: docker build -f go.dockerfile -t gohcmus/logic-app:v2 .

      - name: Push Docker image
        run: docker push gohcmus/logic-app:v2

      - name: Apply K8s manifests
        run: |
          kubectl apply -f mysql.yaml
          kubectl apply -f kafka.yaml
          kubectl apply -f deployment.yaml

      - name: Wait for rollout
        run: kubectl rollout status deployment myapp
